name: iot Connector Health Checker Staging1
version: 0.2.1
uptime:
  baseUrl: https://metrics.uptime.com/metrics/heartbeat
checksConfigurations:
  - hostname: gw.staging.iot-connector.wunder.tools
    port: 27261
    uptimeCheck: KCUY-74B0D2473E8C2344

  - hostname: gw.staging.iot-connector.wunder.tools
    port: 27262
    uptimeCheck: KCUM-A43358902E41DDC0
