name: deploying test

on:
  push:
    branches:
      - master
    paths:
      - deployments/**


jobs:
  changed-files:
    name: detect changed files
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.changes.outputs.all}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
  
  deploy-staging:
    name: deploy staging
    runs-on: ubuntu-latest
    needs: changed-files
    # if: ${{contains(needs.changedfiles.outputs.files, 'staging.yml')}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: detect changes
        id: changes
        run: |
          echo "${{ needs.changedfiles.outputs.files }}"

