name: deploying test

on:
  push:
    branches:
      - master
    paths:
      - deployments/**


jobs:
  changed-files:
    name: detect changed files
    runs-on: ubuntu-latest
    outputs:
      staging: ${{ steps.changes.outputs.staging }}
      production: ${{ steps.changes.output.production }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        run: |
          # See https://github.community/t/check-pushed-file-changes-with-git-diff-tree-in-github-actions/17220/10
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            git fetch origin $GITHUB_BASE_REF --depth=1
            export DIFF=$( git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA )
            echo "Diff between origin/$GITHUB_BASE_REF and $GITHUB_SHA"
          else
            # Push
            git fetch origin ${{ github.event.before }} --depth=1
            export DIFF=$( git diff --name-only ${{ github.event.before }} $GITHUB_SHA )
            echo "Diff between ${{ github.event.before }} and $GITHUB_SHA"
          fi
          echo "$DIFF"
          for file in $DIFF; do
              if [[ $file == *"deployments/staging.json"* ]]; then
                  echo "::set-output name=staging::$( echo "1" )"
              fi
              if [[ $file == *"deployments/production.json"* ]]; then
                  echo "::set-output name=production::$( echo "1" )"
              fi
          done
  
  deployment:
    name: deploy staging
    runs-on: ubuntu-latest
    needs: changed-files
    if: ${{ needs.changed-files.outputs.staging == '1' }}
    steps: 
      - name: set env variables
        run: |
          echo "ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "CONFIG=$(cat deployments/staging.json)" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2
      - name: detect changes
        id: changes
        run: |
          echo "running $ENVIRONMENT => $CONFIG"