name: deploying test

on:
  push:
    branches:
      - master
    paths:
      - deployments/**


jobs:
  changed-files:
    name: detect changed files
    runs-on: ubuntu-latest
    outputs:
      staging: ${{ steps.changes.outputs.staging }}
      production: ${{ steps.changes.output.production }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get changed files
        id: changes
        run: |
          # Get the current ip adderss 
          IP_ADD=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')
          echo $IP_ADD;